POST http://127.0.0.1:3001/api/questions
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWQiOiI2MTM4OTNlODU1Y2Y0Y2JlY2I4Y2RiMzIiLCJpYXQiOjE2MzEwOTgzMDV9.4djzRIQkD06k26GhbxzxSWUHWmsF5Y_AZiWeXw81JXY

{
    "optionOne": "optionOne",
    "optionTwo": "optionTwo"
}